### ISSUE TITLE
precenceCannel.member does not exist

### ISSUE THREAD

**Issue by SergeyTroshkov** [pusher/pusher-websocket-dotnet#100]
![image](https://user-images.githubusercontent.com/64059970/79829271-ccc12b00-83cc-11ea-8d49-e59144fc7145.png)

How to make it work?
There is no way to get users the presence channel since properties (memberAdded, memberRemoved, members) are not available

**Comment by SergeyTroshkov** [comment]
it's in Unity

**Comment by benw-pusher** [comment]
This can be achieved using the example provided at https://github.com/pusher/pusher-websocket-dotnet#presence-channels.
