### ISSUE TITLE
ConnectAsyn exception

### ISSUE THREAD

**Issue by speedy78** [pusher/pusher-websocket-dotnet#101]
Hello,
I'm using the PusherClient in few installation and it works fine. But in the latest installation I'm getting a strange error.

This is the flow:

- Pusher is connected
- Then due to exception the connection is lost
- On reconnect it gets "System.exception: accept key doesn't match"

See the image below:

![image](https://user-images.githubusercontent.com/14369251/83417217-1405f700-a422-11ea-8497-02dc630475ed.png)

Can you help me?

**Comment by lapoPaolacci** [comment]
I've the same problem

**Comment by elverkilde** [comment]
This issue was fixed in #104 which was released as version `2.0.0`. Please be aware that this is a major release, with several breaking changes. We have written a migration guide here: 

https://github.com/pusher/pusher-websocket-dotnet#migrating-from-version-1-to-version-2
