### ISSUE TITLE
How to bind to "pusher: subscription_succeeded" event?

### ISSUE THREAD

**Issue by mab09** [pusher/pusher-websocket-dotnet#103]
Hello,
I do not recieve a "pusher: subscription_succeeded" event when I bind my channel to it. 
I am guessing that something like 
```
_updatesChannel = await pusher.SubscribeAsync(_uChannel);
_updatesChannel.Subscribed += OnUChannelSubscribed;
```
Is to accomplish that but the ".Subscribed" doesn't always gets triggered,  I have many such channels and I only get "OnUChannelSubscribed()" for only 1-2 of them, probably because for some the ".Subscribed" gets triggered even before it is set to activate "OnUChannelSubscribed()".

I am basically looking to get the correct number of subscription success messages before whatever bindings I make to those channels

Thanks

**Comment by mab09** [comment]
For now doing a BindAll/Bind with the pusher object instead of the channel object seem to give the feedback messages that I am looking for. 
Feel free to close the issue.

**Comment by ben-pusher** [comment]
Thanks @mab09. We will close this as it doesn't appear to be a bug with the lib. 
Glad you;ve found a solution using bindall.
