### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by RobertoSchneiders** [pusher/pusher-websocket-dotnet#11]
this lib does not support proxy, right?

What do you think of this approach? http://stackoverflow.com/a/23417094/1847499

**Comment by RobertoSchneiders** [comment]
Another reference https://github.com/kerryjiang/WebSocket4Net/issues/34

**Comment by leggetter** [comment]
Also asked here http://stackoverflow.com/questions/33918530/c-sharp-websocket-with-proxy/

If something were to be done with this the public API should probably be to set a `Proxy` property on the [PusherOptions](https://github.com/pusher-community/pusher-websocket-dotnet/blob/master/PusherClient/PusherOptions.cs) class and pass an instance in to the `Pusher` constructor.
