### ISSUE TITLE
A call to SSPI could not be made; see inner exception (.NET Framework 4.5 and 4.7.2)

### ISSUE THREAD

**Issue by rsimonru** [pusher/pusher-websocket-dotnet#113]
Hello.

I'm getting the error "A call to SSPI could not be made; see inner exception" in ConnectAsync() in a C# project with .NET Framework 4.5 & 4.7.2. When use .NET Core 3.1, the application work perfect.

What could be wrong?

**Comment by benw-pusher** [comment]
Could you share the full exception (including the mentioned inner exception)?

**Comment by OlegRa** [comment]
The WebSocket4Net package has known problems with secure socket connections (see [this](https://github.com/kerryjiang/WebSocket4Net/issues/193) and [this](https://github.com/kerryjiang/WebSocket4Net/issues/185) issue) that prevent connecting to Pusher servers from .NET Framework applications.
As a workaround, I've personally switched from the .NET Framework versions of this library to the .NET Standard version. it works fine but as a long-term solution, the new version of WebSocket4Net or another web socket library should be considered.
