### ISSUE TITLE
Update from 1.2 to 2.1 changed JSON structure

### ISSUE THREAD

**Issue by SmileSoftSr** [pusher/pusher-websocket-dotnet#115]
I've updated the libraries in one of my Pusher projects (1.2 to 2.1) via NuGet Package manager in VS 2015, and all of a sudden, my JSON parsing is not working anymore. After checking why, it seems that the structure of the received JSON was changed.

Instead of this:

```
{
	"event": "myevent",
	"data": {
		"message": {
			"header": {
				"type": "type1",
				"printer": "myprinter"
			},
			"items": {
				"1": "Item 1@03@Kg@1@1782.00@1782.00@6002@03"
			},
			"info": {
				"type": "stuff",
				"other": "yes"
			}
		}
	},
	"channel": "mychannel"
}
```

the JSON now looks like this

```
{
	event = cashregister,
	data = {
		"message": {
			"header": {
				"type":"type1",
				"printer":"myprinter"
			},
			"items": {
				"1":"Item 1@03@Kg@1@1782.00@1782.00@6002@03"
			},
			"info": {
				"type":"stuff",
				"other":"yes"
			}
		}
	},
	channel = mychannel,
	user_id =  
}
```

Short of downgrading back to 1.2, how can I get the JSON structure I had before? Please note that nothing was changed on the sending end - the JSON structure is the same as before the upgrade.

**Comment by elverkilde** [comment]
The structure you are referring to seems to be in the opaque payload for the internals of the SDK. The user of the SDK would normally only interact with what's inside the `data` field, which in this case seems to be the same.

Which method/callback in the SDK are you using to get the raw JSON payload?
