### ISSUE TITLE
It works, just once.

### ISSUE THREAD

**Issue by Mittchel** [pusher/pusher-websocket-dotnet#14]
Hi,

I've been trying to port this library for Xamarin and to be honest it's pretty easy since WebSocket4Net also Supports Xamarin. Only thing I had to do was remove the Settings since Xamarin doesn't have System.Configuration.

So, I subscribed to a private channel with the following code: 

> ```
>       var _chatChannel = pusher.Subscribe ("channelname");
>         _chatChannel.Subscribed += _chatChannel_Subscribed;
>         _chatChannel.Bind("NEW_MESSAGE", (data) =>
>             {
>                 Console.WriteLine("[" + data.name + "] " + data.message);
>             });
> ```

It seems to work.. the event fires when I send a message with event name NEW_MESSAGE. But as soon as I send another one it doesn't come into the Bind anymore so the event is not caught..

Any ideas what this might be?

**Comment by erichedstrom** [comment]
@Mittchel Hi, have you had any luck getting past this? I just ran into the same problem in a Xamarin Android app.

Thanks!

**Comment by erichedstrom** [comment]
If anyone else runs into this and ends up here, I got it to work by binding my channel to an async action: 

                channel.Bind("data-change", async data =>
                {
                    var jsonData = data as JObject;

                    if (jsonData != null)
                    {
                         // .... do stuff
                         await MyAsyncTask();
                    }
                });
