### ISSUE TITLE
presence channel member Removed, how to know easily which member is removed?

### ISSUE THREAD

**Issue by carldarlenspierre** [pusher/pusher-websocket-dotnet#35]
Hi,

based on the following closed issue
https://github.com/pusher-community/pusher-websocket-dotnet/issues/15

is it possible able to have the same thing for remove event event handler ?

channel.MemberRemoved += (sender, memberData) =>
{

};

It will be really helpful to have the updated list of members and the member recently removed from the channel

**Comment by elverkilde** [comment]
This issue was fixed in #104 which was released as version `2.0.0`. Please be aware that this is a major release, with several breaking changes. We have written a migration guide here: 

https://github.com/pusher/pusher-websocket-dotnet#migrating-from-version-1-to-version-2
