### ISSUE TITLE
Please make a  version for .net Core 2.0

### ISSUE THREAD

**Issue by kooboo-binbin** [pusher/pusher-websocket-dotnet#45]
Please make a  version for .net Core 2.0

**Comment by imaji** [comment]
Hi,

Yes, we're just looking at timescales to make a .net standard compliant version.

I haven't got a date for you yet though.

Best regards,
John

**Comment by nicolasguzca** [comment]
Hi John, any updates on the .net Core 2.0 version?

**Comment by justin-lavelle** [comment]
I have a fork for netstandard2.0 https://github.com/justin-lavelle/pusher-websocket-dotnet-netstandard

**Comment by Misiu** [comment]
@justin-lavelle could You make a PR with all the changes?

**Comment by imaji** [comment]
I've got a version we're going to merge in shortly that adds in support for .net standard 1.6 & 2.0

**Comment by Misiu** [comment]
@imaji awesome news 😄

**Comment by Misiu** [comment]
@imaji any updates?

**Comment by Misiu** [comment]
ping

**Comment by kn100** [comment]
Hi @Misiu - I will also bring this up in our next standup and keep you up to date on our plans.

**Comment by Misiu** [comment]
@kn100 any news from standup?

**Comment by Misiu** [comment]
@kn100 any updates?

**Comment by Misiu** [comment]
@damdo any updates?

**Comment by damdo** [comment]
Hey all! So currently the library supports .NET standard 1.6, but yes .NET standard 2.0 (and thus .NET Core 2.0) is on our radar. We are currently focused on improving certain behaviours of the library / fixing some issues, but extending the compatibility is next 👍

**Comment by elverkilde** [comment]
This issue was fixed in #104 which was released as version `2.0.0`. Please be aware that this is a major release, with several breaking changes. We have written a migration guide here: 

https://github.com/pusher/pusher-websocket-dotnet#migrating-from-version-1-to-version-2
