### ISSUE TITLE
How to update the headers?

### ISSUE THREAD

**Issue by redswimmer** [pusher/pusher-websocket-dotnet#49]
I'm trying to add a bearer token but don't see a way to update the headers.

**Comment by DubMatrix** [comment]
Just create your own implementation of interface IAuthorizer (you can use HttpAuthorizer as a start). Then just add anything you like to the Authorize() function, like:

    public class MyAuthorizer : IAuthorizer
    {
        private Uri _authEndpoint;
        public MyAuthorizer (string authEndpoint)
        {
            _authEndpoint = new Uri(authEndpoint);
        }

        public string Authorize(string channelName, string socketId)
        {
            string authToken = null;

            using (var webClient = new System.Net.WebClient())
            {
                string data = String.Format("channel_name={0}&socket_id={1}", channelName, socketId);
                webClient.Headers[HttpRequestHeader.ContentType] = "application/x-www-form-urlencoded";
                webClient.Headers[HttpRequestHeader.Accept] = "application/json";
                webClient.Headers[HttpRequestHeader.Authorization] = "my_auth_code";
                authToken = webClient.UploadString(_authEndpoint, "POST", data);
            }
            return authToken;
        }
    }
