### ISSUE TITLE
Implement ConnectAsync

### ISSUE THREAD

**Issue by brianfeucht** [pusher/pusher-websocket-dotnet#5]
Rather than waiting for an event to return, provide a method which will is an awaitable connect.

**Comment by brianfeucht** [comment]
I am currently implementing this via:
```
        private async Task<PusherClient.Pusher> CreateOpenPusher(string appKey)
        {
            var pusherClient = new PusherClient.Pusher(appKey);

            var tcs = new TaskCompletionSource<bool>();
            pusherClient.Connected += (s) => tcs.TrySetResult(true);
            pusherClient.Connect();

            await tcs.Task;

            return pusherClient;
        }
```

It would be nice if there was a less naive implementation.

**Comment by leggetter** [comment]
@brianfeucht One of the reasons we moved this under the pusher-community organisation is that it's a repo that we don't have the time to officially maintain right now. So, if you are able to submit a pull request for this functionality it would be greatly received.

If not, I'll keep the issue open to keep track of the demand for this.

**Comment by damdo** [comment]
Added in https://github.com/pusher/pusher-websocket-dotnet/releases/tag/1.0.0-beta
