### ISSUE TITLE
Pusher connetion stuck on connecting

### ISSUE THREAD

**Issue by yuyenkan** [pusher/pusher-websocket-dotnet#57]
My pusher connection repeating on connecting -> disconnected -> waiting to reconnecting, I am sure the cluster and app key is correct.

There is no error throw to error event and trace is empty also.

I checked debug console in pusher
![image](https://user-images.githubusercontent.com/22000244/51149350-aabd2c80-189c-11e9-8a49-864bc6e6239d.png)

it is repeating connection and disconnection

**Comment by Misiu** [comment]
@yuyenkan what library are You talking about? This might help others having similar/same problem

**Comment by damdo** [comment]
Hey @yuyenkan glad that you found a solution to your issue! I'm closing this issue but it might be useful if you can specify which dependency library was causing your issue! Thank you
