### ISSUE TITLE
How to update the Host?

### ISSUE THREAD

**Issue by vitalik8545** [pusher/pusher-websocket-dotnet#58]
I want to change Host in class PusherOptions. What i want to do for this?

**Comment by imaji** [comment]
Hi,

The only customisation supported at the moment is changing the cluster, how did you want to change the host?

Thanks,
John

**Comment by kiranmaya** [comment]
in this js pusher cliet https://developers.liquid.com/#authenticated
they were changing wshost . in c# libarary is there any way of doing it.

**Comment by snax4a** [comment]
I also need to set The host and wsPort like in js library

**Comment by simonbuehler** [comment]
Changing the host string in options class should do it
