### ISSUE TITLE
Incompatibility with il2cpp due to dynamic keyword

### ISSUE THREAD

**Issue by cdauphinee** [pusher/pusher-websocket-dotnet#69]
I have a Unity 2019.2 project that builds for iOS, using the il2cpp scripting back-end. At run time, I receive the following exception whenever a `dynamic` is read or written to (i.e. receiving messages or subscribing to a presence channel):
```
[Exception] NullReferenceException: Object reference not set to an instance of an object.
    System.Linq.Expressions.Interpreter.LightLambda.MakeRunDelegateCtor (System.Type delegateType) (at <00000000000000000000000000000000>:0)
    System.Linq.Expressions.Interpreter.LightLambda.GetRunDelegateCtor (System.Type delegateType) (at <00000000000000000000000000000000>:0)
    System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate (System.Type delegateType) (at <00000000000000000000000000000000>:0)
    System.Linq.Expressions.Expression`1[TDelegate].Compile (System.Boolean preferInterpretation) (at <00000000000000000000000000000000>:0)
    System.Runtime.CompilerServices.CallSite`1[T].MakeUpdateDelegate () (at <00000000000000000000000000000000>:0)
    System.Runtime.CompilerServices.CallSite`1[T].GetUpdateDelegate (T& addr) (at <00000000000000000000000000000000>:0)
    System.Runtime.CompilerServices.CallSite`1[T]..ctor (System.Runtime.CompilerServices.CallSiteBinder binder) (at <00000000000000000000000000000000>:0)
    System.Runtime.CompilerServices.CallSite`1[T].Create (System.Runtime.CompilerServices.CallSiteBinder binder) (at <00000000000000000000000000000000>:0)
```

It seems like it's trying to do run-time code generation. To my knowledge, this isn't supported by il2cpp (and not allowed on iOS, even if it were supported). I suspect the same problem is also present on Android builds.

Looking at the code, I came up with two quick solutions that would fix this:
1. Replace internal deserialization to `dynamic` (i.e. used for presence channels) with classes.
2. Replace the usage of `dynamic` in the EventEmitter callbacks with `string`.
    * Interface compatibility can be maintained by having both `Action<string>` and `Action<dynamic>` overloads, though internally only `Action<string>` is stored
    * This also allows the consumer to decide which JSON library to use for message deserialization, and could be useful if they have custom converters.

I have no problem making these changes myself, but I want to put this out there for discussion before opening a PR.

**Comment by damdo** [comment]
Hey @cdauphinee,
thank you for reporting this and for your overall analysis on the library potential issues. Could you open a PR with your recommended fix? We (me and @imaji) will be more than happy to review it and move forward with this. Thank you.

**Comment by cdauphinee** [comment]
@damdo @imaji
Thanks for the response, I've put up https://github.com/pusher/pusher-websocket-dotnet/pull/77 for early feedback.

**Comment by damdo** [comment]
Resolved by #77

**Comment by Alienide-Interactive** [comment]
thanks cdauphinee. I am doing Replace the usage of dynamic in the EventEmitter callbacks with string as a way arround.

**Comment by dotsquid** [comment]
You could just make Unity not strip required code by using the following [link.xml](https://docs.unity3d.com/Manual/ManagedCodeStripping.html#LinkXML)
`<linker>
  <assembly fullname="System.Core">
    <type fullname="System.Linq.Expressions.Interpreter.LightLambda" preserve="all" />
  </assembly>
</linker>`

**Comment by CavernHead** [comment]
I don't know how to do this: 
-Replace internal deserialization to dynamic. 
-Replace the usage of dynamic in the EventEmitter callbacks with string
I get my issue when i call the JObject.Parse(string)
any help would be appreciated
