### ISSUE TITLE
Unable to recover from a lost connection

### ISSUE THREAD

**Issue by cdauphinee** [pusher/pusher-websocket-dotnet#70]
If I disconnect my machine from the network after connecting to Pusher, I receive three `ConnectionStateChanged` events:
* Disconnected
* WaitingForReconnect
* Initialized

When I reconnect to the network, the client doesn't automatically reconnect. If I try to call `ConnectAsync` to manually reconnect, it returns AlreadyConnected, even though the connection state is Initialized. If I try calling `DisconnectAsync` before reconnecting, I receive the same result.

From the code, it looks like `ConnectAsync` can only be called once per instance. I can work around this by recreating my `Pusher` instance when I lose my connection, but this isn't ideal.

**Comment by ShireOakDan** [comment]
Is there any update on this at all as I am finding the same issue.

Connect used to work fine but now it's been replaced with an Async it doesn't reconnect after network loss which I agree isn't ideal.

**Comment by imaji** [comment]
I'm doing some work in there now. Do you have steps to reproduce?  Ideally a test of some kind?

**Comment by ShireOakDan** [comment]
I can try and post some actual code later as I am away from computer at the moment but as a simple test to reproduce. 

The issue can be achieved using some of the Usage example. 

Connect to pusher and write connection state changes to the console. Disconnect from your network temporarily and then reconnect to the network and the pusher instance won't reconnect. 

Sorry if this isn't clear I'm writing on my mobile!

**Comment by imaji** [comment]
Not at all.

Found it & fixed. The branch I'm working on should be going live shortly.

**Comment by ShireOakDan** [comment]
Just noticed a fix has been pushed for this, excellent work thank you.

When will this get applied to the NuGet package?

**Comment by imaji** [comment]
Yup, going to do some further testing, then it should end up in Nuget shortly :)

**Comment by ShireOakDan** [comment]
Great! Thanks again

**Comment by MPNGZ** [comment]
Hi sorry for jumping on this thread - just found this after doing a little bit of googling of the issue.

I use Nuget and notice you have mentioned you will be updating the package, do you have an ETA on when it will be available as an update please? :)

**Comment by ShireOakDan** [comment]
Just had an alert to say to 1.1.0 was released. Updated package and for some reason the connection doesn't recover.

Steps: Start the application which automatically connects and subscribes, I sent a test event which came through, I then disconnected my WiFi for 30 seconds, and turned it back on and it didn't reconnect.

Not sure if this helps but it's from my connection log:

11/10/2019 14:35:18 - Initialized
11/10/2019 14:35:18 - Initialized
11/10/2019 14:35:20 - Subscribed
11/10/2019 14:35:30 - {
  "event": "App\\Events\\ItemUpdated",
  "data": "{\"item\":\"test\"}",
  "channel": "private-items.test"
}
11/10/2019 14:35:41 - Disconnected
11/10/2019 14:35:41 - Disconnected
11/10/2019 14:35:41 - WaitingToReconnect
11/10/2019 14:35:41 - WaitingToReconnect
11/10/2019 14:35:41 - Initialized
11/10/2019 14:35:41 - Initialized
11/10/2019 14:35:41 - Disconnected
11/10/2019 14:35:41 - Disconnected
11/10/2019 14:35:41 - WaitingToReconnect
11/10/2019 14:35:41 - WaitingToReconnect
