### ISSUE TITLE
HttpAuthorizer returns incorrect auth token

### ISSUE THREAD

**Issue by tyronent** [pusher/pusher-websocket-dotnet#78]
When I run the ExampleApplication I am getting the following error:

"JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0"

Upon further investigation it seems that the error is caused at HttpAuthorizer.Authorize():

`authToken = response.Content.ToString();`

returns "System.Net.Http.StreamContent" instead of the actual response.

For this to work the line needs to be changed to:
`authToken = response.Content.ReadAsStringAsync().Result;`

Is this a known issue?

Note: I am using .net 4.6.1

**Comment by 15mgm15** [comment]
@tyronent  In your code what is `response` ?
