### ISSUE TITLE
403 Forbidden should be handled when authenticating user

### ISSUE THREAD

**Issue by heath3n** [pusher/pusher-websocket-dotnet#89]
According to [the docs](https://pusher.com/docs/channels/server_api/authenticating-users#general-notes), the server should handle a rejected authentication by sending a `403 Forbidden` status. In practice, this causes an NRE. We are working around this by ensuring we send back a body with the key `auth` like `{ auth: 'invalid'}` but it would be great if the library could just recognize an error occurred from the status code.

**Comment by elverkilde** [comment]
This issue was fixed in #104 which was released as version `2.0.0`. Please be aware that this is a major release, with several breaking changes. We have written a migration guide here: 

https://github.com/pusher/pusher-websocket-dotnet#migrating-from-version-1-to-version-2
